use super::*;
use std::fs;
use tempfile::TempDir;

fn fixture() -> (TempDir, PathBuf) {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path();
    fs::create_dir(root.join(".git")).unwrap();
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(root.join("tests")).unwrap();
    fs::create_dir_all(root.join("dep/src")).unwrap();
    fs::write(root.join("Cargo.toml"), "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n[dependencies]\ndep = { path = \"dep\" }\n").unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"dep\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"fixture\"\nversion = \"0.1.0\"\ndependencies = [\n \"dep\",\n]\n",
    )
    .unwrap();
    fs::write(
        root.join("dep/Cargo.toml"),
        "[package]\nname = \"dep\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(root.join("dep/src/lib.rs"), "pub struct Dependency;\n").unwrap();
    fs::write(root.join("src/lib.rs"), "pub mod api;\npub use crate::api::Thing as PublicThing;\nuse std::{fmt as formatting, collections::*};\n#[derive(Debug)] pub struct Thing;\npub trait Runner { fn run(&self); }\nimpl Thing { pub fn execute() {} }\nimpl Runner for Thing { fn run(&self) {} }\npub fn call() { api::Thing; }\n#[cfg(test)] mod inner { #[test] fn unit_case() { super::Thing::execute(); super::call(); } }\n").unwrap();
    fs::write(root.join("src/api.rs"), "pub struct Thing;\n").unwrap();
    fs::write(
        root.join("tests/integration.rs"),
        "#[test] fn integration_case() {}\n",
    )
    .unwrap();
    let state = temp.path().join(".git/cabal-runtime/repository-map");
    (temp, state)
}
fn index(temp: &TempDir, state: &Path) -> RepositoryMapIndex {
    refresh(temp.path(), state).unwrap().index
}

#[test]
fn deterministic_bytes_and_known_syntactic_corpus() {
    let (temp, state) = fixture();
    let first = index(&temp, &state);
    assert!(
        !first
            .files
            .iter()
            .any(|file| file.path.starts_with(".git/"))
    );
    let raw_first = fs::read(state.join(INDEX_FILE)).unwrap();
    let second = index(&temp, &state);
    let raw_second = fs::read(state.join(INDEX_FILE)).unwrap();
    assert_eq!(raw_first, raw_second);
    assert_eq!(first, second);
    assert_eq!(find_symbols(&first, "Thing").len(), 2);
    assert_eq!(find_imports(&first, "std::fmt").len(), 1);
    assert!(!find_references(&first, "api::Thing").is_empty());
    assert_eq!(find_tests(&first, "integration_case").len(), 1);
    assert_eq!(find_symbols(&first, "Thing::execute").len(), 1);
    assert_eq!(find_symbols(&first, "Runner::run").len(), 1);
    let associated = find_associated_tests(&first, "Thing::execute");
    assert_eq!(associated.len(), 1);
    assert_eq!(associated[0].test.name, "unit_case");
    let file = first
        .files
        .iter()
        .find(|file| file.path == "src/lib.rs")
        .unwrap();
    let RustParseStatus::Parsed { facts } = &file.rust else {
        panic!("Rust corpus must parse");
    };
    assert!(facts.modules.iter().any(|module| module.name == "api"));
    assert!(
        facts
            .definitions
            .iter()
            .any(|definition| definition.name == "call")
    );
    assert!(
        facts
            .reference_edges
            .iter()
            .any(|path| path == "api::Thing")
    );
}

#[test]
fn refresh_reuses_changes_and_deletes() {
    let (temp, state) = fixture();
    let first = index(&temp, &state);
    assert_eq!(first.files.len(), 7);
    let unchanged = refresh(temp.path(), &state).unwrap();
    assert_eq!(unchanged.reused_files, 7);
    assert_eq!(unchanged.reparsed_files, 0);
    fs::write(temp.path().join("src/api.rs"), "pub struct Changed;\n").unwrap();
    let changed = refresh(temp.path(), &state).unwrap();
    assert_eq!(changed.reparsed_files, 1);
    assert_eq!(changed.reused_files, 6);
    fs::remove_file(temp.path().join("tests/integration.rs")).unwrap();
    let deleted = refresh(temp.path(), &state).unwrap();
    assert_eq!(deleted.deleted_files, 1);
    assert!(
        !deleted
            .index
            .files
            .iter()
            .any(|file| file.path == "tests/integration.rs")
    );
}

#[test]
fn malformed_oversize_and_bounds_are_explicit() {
    let (temp, state) = fixture();
    fs::write(temp.path().join("src/broken.rs"), "fn {\n").unwrap();
    fs::write(
        temp.path().join("src/large.rs"),
        vec![b'x'; MAX_INDEXED_FILE_BYTES as usize + 1],
    )
    .unwrap();
    let result = index(&temp, &state);
    assert_eq!(result.omissions.malformed_rust, 1);
    assert_eq!(result.omissions.oversized_files, 1);
    assert_ne!(result.completeness, Completeness::Complete);
    assert!(matches!(
        result
            .files
            .iter()
            .find(|file| file.path == "src/broken.rs")
            .unwrap()
            .rust,
        RustParseStatus::Malformed
    ));
    assert!(matches!(
        result
            .files
            .iter()
            .find(|file| file.path == "src/large.rs")
            .unwrap()
            .rust,
        RustParseStatus::Oversized
    ));
    assert!(
        result
            .files
            .iter()
            .find(|file| file.path == "src/large.rs")
            .unwrap()
            .sha256
            .is_none()
    );
}

#[test]
fn corrupt_and_incompatible_index_rebuilds() {
    let (temp, state) = fixture();
    fs::create_dir_all(&state).unwrap();
    fs::write(state.join(INDEX_FILE), b"not json").unwrap();
    assert!(load(&state).unwrap().is_none());
    let rebuilt = refresh(temp.path(), &state).unwrap();
    assert_eq!(rebuilt.index.schema, INDEX_SCHEMA);
    let mut incompatible = rebuilt.index;
    incompatible.schema = "old".to_owned();
    fs::write(
        state.join(INDEX_FILE),
        serde_json::to_vec(&incompatible).unwrap(),
    )
    .unwrap();
    assert!(current(&state).unwrap().is_none());
}

#[test]
fn cargo_fixture_and_projection_do_not_leak() {
    let (temp, state) = fixture();
    fs::write(temp.path().join(".hidden.rs"), "pub struct Hidden;\n").unwrap();
    let value = index(&temp, &state);
    assert!(value.cargo.available);
    assert!(
        value
            .cargo
            .packages
            .iter()
            .any(|package| package.name == "fixture")
    );
    assert!(
        value
            .cargo
            .dependency_edges
            .iter()
            .any(|edge| edge.dependency == "dep")
    );
    assert!(
        value
            .cargo
            .packages
            .iter()
            .flat_map(|package| &package.targets)
            .any(|target| target.kinds.iter().any(|kind| kind == "lib"))
    );
    let inventory = inventory(&value);
    let raw = String::from_utf8(inventory_bytes(&inventory)).unwrap();
    assert!(raw.len() <= MAX_INVENTORY_BYTES);
    assert!(!raw.contains(&temp.path().to_string_lossy().to_string()));
    assert!(!raw.contains("pub struct Thing"));
    assert!(!raw.contains("repository-map"));
    assert_eq!(inventory.schema, INVENTORY_SCHEMA);
    let visible = visible_inventory(&value);
    assert!(!visible.source_paths.iter().any(|path| path == ".hidden.rs"));
    assert!(visible.omitted_files >= 1);
    assert!(!visible.projection_complete);
    assert!(
        estimated_visible_file_list_bytes(&value)
            < value.files.iter().map(|file| file.path.len() + 1).sum()
    );
}

#[test]
fn manifest_change_refreshes_cargo_facts_and_gitignore_is_obeyed() {
    let (temp, state) = fixture();
    fs::write(temp.path().join(".gitignore"), "ignored.rs\n").unwrap();
    fs::write(temp.path().join("ignored.rs"), "pub fn ignored() {}\n").unwrap();
    let first = index(&temp, &state);
    assert!(!first.files.iter().any(|file| file.path == "ignored.rs"));
    fs::write(
        temp.path().join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.2.0\"\nedition = \"2024\"\n[dependencies]\ndep = { path = \"dep\" }\n",
    )
    .unwrap();
    fs::write(
        temp.path().join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"dep\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"fixture\"\nversion = \"0.2.0\"\ndependencies = [\n \"dep\",\n]\n",
    )
    .unwrap();
    let changed = index(&temp, &state);
    assert!(
        changed
            .cargo
            .packages
            .iter()
            .any(|package| package.name == "fixture" && package.version == "0.2.0")
    );
}

#[test]
fn cargo_collection_never_creates_a_missing_lockfile() {
    let temp = tempfile::tempdir().unwrap();
    fs::create_dir(temp.path().join(".git")).unwrap();
    fs::create_dir(temp.path().join("src")).unwrap();
    fs::write(
        temp.path().join("Cargo.toml"),
        "[package]\nname = \"unlocked\"\nversion = \"0.1.0\"\nedition = \"2024\"\n[dependencies]\nserde = \"1\"\n",
    )
    .unwrap();
    fs::write(temp.path().join("src/lib.rs"), "pub struct Source;\n").unwrap();
    let state = temp.path().join(".git/cabal-runtime/repository-map");

    let result = refresh(temp.path(), &state).unwrap();

    assert!(!result.index.files.is_empty());
    assert!(!temp.path().join("Cargo.lock").exists());
    assert!(!temp.path().join("target").exists());
}

#[test]
fn collector_and_projection_limits_are_hard_and_reported() {
    let (temp, state) = fixture();
    let mut crowded = String::new();
    for index in 0..(MAX_RUST_SYMBOLS_PER_FILE + 2) {
        crowded.push_str(&format!("fn symbol_{index}() {{ Thing; }}\n"));
    }
    for _ in 0..(MAX_IMPORTS_PER_FILE + 2) {
        crowded.push_str("use std::fmt;\n");
    }
    fs::write(temp.path().join("src/crowded.rs"), crowded).unwrap();
    let value = index(&temp, &state);
    let crowded = value
        .files
        .iter()
        .find(|file| file.path == "src/crowded.rs")
        .unwrap();
    let RustParseStatus::Parsed { facts } = &crowded.rust else {
        panic!("crowded file must parse");
    };
    assert_eq!(facts.definitions.len(), MAX_RUST_SYMBOLS_PER_FILE);
    assert_eq!(facts.imports.len(), MAX_IMPORTS_PER_FILE);
    assert!(facts.omissions.symbols >= 2);
    assert!(facts.omissions.imports >= 2);
    assert_eq!(facts.references.len(), MAX_RUST_REFERENCES_PER_FILE);
    assert!(facts.omissions.references >= 2);

    let mut projected = RepositoryInventory {
        schema: INVENTORY_SCHEMA.to_owned(),
        indexed_files: 300,
        projected_files: 0,
        omitted_files: 0,
        source_paths: (0..300)
            .map(|index| format!("src/{index}-{}", "x".repeat(512)))
            .collect(),
        test_paths: Vec::new(),
        manifest_paths: Vec::new(),
        configuration_paths: Vec::new(),
        packages: Vec::new(),
        indexed_packages: 0,
        omitted_packages: 0,
        indexed_targets: 0,
        omitted_targets: 0,
        projection_complete: true,
        completeness: Completeness::Complete,
    };
    bound_inventory(&mut projected);
    update_inventory_counts(&mut projected, 0);
    assert!(total_inventory_paths(&projected) <= MAX_INVENTORY_PATHS);
    assert!(inventory_bytes(&projected).len() <= MAX_INVENTORY_BYTES);
    assert_eq!(projected.omitted_files, 300 - projected.projected_files);
    assert!(!projected.projection_complete);
}

#[test]
fn rejects_missing_git_or_external_state_root() {
    let temp = tempfile::tempdir().unwrap();
    fs::create_dir_all(temp.path().join("src")).unwrap();
    assert!(matches!(
        refresh(temp.path(), &temp.path().join("state")),
        Err(RepositoryMapError::NoGitServiceDirectory)
    ));
    fs::create_dir(temp.path().join(".git")).unwrap();
    assert!(matches!(
        refresh(temp.path(), tempfile::tempdir().unwrap().path()),
        Err(RepositoryMapError::StateRootOutsideGitService)
    ));
}

#[test]
fn concurrent_refreshes_are_serialized_and_leave_valid_state() {
    let (temp, state) = fixture();
    let workspace = temp.path().to_path_buf();
    let handles = (0..6)
        .map(|_| {
            let workspace = workspace.clone();
            let state = state.clone();
            std::thread::spawn(move || refresh(&workspace, &state).unwrap())
        })
        .collect::<Vec<_>>();
    for handle in handles {
        assert!(!handle.join().unwrap().index.files.is_empty());
    }
    assert!(load(&state).unwrap().is_some());
}

#[cfg(unix)]
#[test]
fn symlinks_are_omitted_without_traversal() {
    use std::os::unix::fs::symlink;
    let (temp, state) = fixture();
    symlink(temp.path().join("src"), temp.path().join("linked-src")).unwrap();
    let value = index(&temp, &state);
    assert_eq!(value.omissions.symlinks, 1);
    assert!(
        !value
            .files
            .iter()
            .any(|file| file.path.starts_with("linked-src/"))
    );
}

#[cfg(unix)]
#[test]
fn state_root_symlink_escape_is_rejected() {
    use std::os::unix::fs::symlink;
    let (temp, _) = fixture();
    let external = tempfile::tempdir().unwrap();
    let runtime_root = temp.path().join(".git/cabal-runtime");
    fs::create_dir(&runtime_root).unwrap();
    let state = runtime_root.join("repository-map");
    symlink(external.path(), &state).unwrap();

    assert!(matches!(
        refresh(temp.path(), &state),
        Err(RepositoryMapError::StateRootOutsideGitService)
    ));
    assert!(external.path().read_dir().unwrap().next().is_none());
}
